//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mashkarin777
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_objectives
    {
        public int Id { get; set; }
        public Nullable<int> Id_project { get; set; }
        public Nullable<int> Id_task { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
    }
}
